import Image from "next/image";
import Link from "next/link";
import entryStyles from "../../styles/entry.module.css";

export default function Page() {
  return (
    <main className={entryStyles.entryStyles}>
      <div className={entryStyles.writingTop}>
        <h2><span className="subnav"><Link href="/journal" className="breadcrumb">Jenny&rsquo;s Journal</Link>The Great Weird</span></h2>
      </div>
      
      <Image
        className={entryStyles.writingHero}
        src="/journal-graphics/the-great-weird.jpg"
        alt="Project"
        width={2880}
        height={2025}
        style={{ width: '100%', height: 'auto' }}
        quality={100} 
        priority
      />

      <div className={entryStyles.body}>
        <h1>The Great Weird</h1>
        <h6>September 2024</h6>
        <h6>9 min read</h6>
        <p>This may be a weird piece of writing. I’ve committed September to embracing my great, internal weird. This process begins with a self-indulgent hibernation, during which my phone is on Do Not Disturb and I sleep as much as I feel and I must spend midday reading and journaling in the sun and I will not be allowed drugs or alcohol before 7pm.</p>
          
        <p>I’ve had a harrowing year, to be honest. I’ve endured the hectic toll of balancing my Masters, work, and social life, then the house troubles, pet health issues, breakups, and leaving my job. This is my first breath in a while. In the face of so many metaphorical life potholes, I wanted to give myself full freedom to rediscover my sense of self. I’ve historically tended toward neuroticism, but oddly, thanks to the critical mass of life experiences I’ve collected recently, I felt like I got to a point where I could successfully embrace and integrate all those emotions and lessons once and for all and begin taking the work of fostering inner stability seriously. Like, “I’ve seen enough and I’m ready to get my shit together now.” So the goal has been to rest and recover, then recalibrate my positions on a mix of matters, from self-love to routine to career direction to friendship. I’m almost through it all now. Through the rest of the month, I will gradually let up the bars, take up my projects again, schedule work time, structure my days.</p>

        <p>I left my job on the last Friday of August with nothing lined up. My current employment is to bask in the sun while the rest of the city sequesters into their occupations, then to paint big and sing loud while everyone else is tucked into bed. I’ll be awake for 24 hours at a time, then sleep for 14 or something hours. I’m reminded how nice it can be to live a no-commitment, ungrounded schedule. I can stay up as late as I want. I’m able to float to any part of town, any street, lot, tree, corner, crowd that is interesting to me. And I like that weekday quiet, flitting around the unbusy city based on the whispers of my heart or whatever. I like the chess tables in the park across the street. I like the cacti in the Rockefeller Park Greenhouse. I like the font of the signs in the Cleveland Metroparks. I like when my red heels match my paperback novel match the cafe patio table I’m seated at match the cappuccino mug match the Acura hatchback parked on the street next to me. I like when things are invisible to everyone else, like a secret in plain sight.</p>

        <p>I opened the first day of my hibernation reading Jack Halberstam, a scholar of queer and gender studies. I had wondered that morning whether my creative reluctance and writing blocks in the last year have to do with betraying my gender, or misunderstanding it. I identify as a woman in the physical way, and I know I had veered from my femininity due to the throes of work stress, house stress, living-alone-in-your-20s stress. I do need to prioritize being calm and evaluative again, and to be confident in my wants. I had a separate thought, though, that beyond all this, I was something else metaphysically that I had been ignoring. Certainly there is something inside me that is more symbolic and non-human. On a morning walk, I couldn’t help but feel like I identified most as a shape: specifically, a five-point star with slightly rounded corners. Sharp, contrasting, ridged edges, but actually pretty simple and surprisingly mild — the rounded corners soften the shape. In general, a star shape is dynamic and multi-armed. The rays seem to want to poke and fit into crevices, the way that squares and triangles might easily slide into a corner. But the rays of a star are so close and its angles are so deep that the star doesn’t really pair easily with other shapes. The virtue of the star is that it’s a clear and unmysterious geometric form, but it’s also a misfit, being so angular and curious. It has many personal crevices. In its best performances, it stands on its own, powerful, symmetrical, and balanced. “I think I’m a star,” I thought to myself, “but like, literally.”</p>

        <p>When I was 21 and inexperienced, I tried several meditation retreats in Los Angeles to, you know, tame the great, internal weird. The one I got the furthest with was a pranayama technique called kriya, which focused on a simple routine of increasingly deeper levels of breathing. I did it consistently for almost two months after the 4-day retreat. It was really good — I recall feeling an emotional clarity begin to open in the stomach — but the practice soon fizzled out as my young, pliable willpower was inevitably redirected to new distractions and callings. I guess there were too many crevices in my life that the kriya couldn’t fill with peace at the time, or at least not fast enough for me. In the next several years, I turned to other shapes and other shapes consumed me, including bulimia and talk therapy and better and worse. But now I know how to soften myself. Today, my meditation practice includes dancing passionately in front of my pets and selecting a different outfit when I have a new errand to run, as to inaugurate every mundanity like a special occasion. It’s in my copious amounts of alone time where I literally lie around on the floor or my bed and do nothing. I’m definitely doing it when I’m enjoying a ginger ale as I walk the dog. Maybe it’s like what some Buddhists do in the zen arts, or even the tantric practices, in which dance and tea and flower arranging and sex are means of creative expression — shaping the present — that can bring about internal stillness. I admire the scrumptious agency I have in every moment and I relent my shame about the unfinished projects, miscommunications, and misshapen outcomes. I eat, or don’t eat, without any guilt. I keep up with the moon and my menstrual cycle, which has helped a lot. I write — I’m writing now again, every day. And I do in fact breathe deeply still. Not as formulaically as with kriya, but often enough and definitely when I need to. At age 27 I seem to naturally know what I’m doing much better now, but it’s always been about being nicer to myself.</p>

        <p>Despite my unemployed status and lack of active income, I’ve committed 600 of my limited dollars to joining a local members-only cocktail club in my neighborhood. Let me explain myself: despite this exorbitant and untimely expense, I think it’s going to be really healing for me, and also good for my personal growth, work ethic, and career to have access to a space like this. It’s a really sweet spot above a bar that I walk by daily with my dog Lila. The staff at the bar love Lila and we’ve built a good connection with them. Owned by the same people, the members club is a private and homey space upstairs that serves custom drinks Thursday through Saturday. They invited me up a few weeks ago to tour it, I was immediately obsessed with the apartment-style layout and the dim lighting and the sofas and the vision and the eclectic maximalist interior design style, and so I applied and put $600 down to join the club for a year. The people are great, I can bring my laptop and just grind through the evenings if I want, it can get playfully rowdy on the weekends, and the drinks are absolutely superb. I know it’ll be the perfect place for me to make new friends in Cleveland because it’s a lowkey scene, but one where I can still get dressed up and meet new people. Simultaneously, it’s also a terrific spot for me to plant myself on a Thursday evening to simply build out my website and finish my Masters thesis this year. I can lounge around and drink. I can read Halberstam and Nussbaum and whatever PDFs I want at 7pm, then dance to Tinashe and Gorillaz with new friends at 10pm. It’s a great investment. It’s a gift to myself.</p>

        <p>As I float around, I notice the contrast between my temporary noncommittal attitude and my actual, real self, who is a very high-commitment, enmeshment-friendly personality. I accept this about myself, and actually, I love it. Yes, I will work on the same project for 5 years. Yes, I will sign up for a 3-year Masters degree program. Yes, I will get the unplanned tattoo. Yes, I will be forward about asking new people I like for their numbers—and I will text them. Yes, I will put in the hours to becoming the best I can be at my hobbies. Yes, I will pay $600 upfront to join a members club for a year. And buying a house is the ultimate enmeshment, and I did that in a city I’d never visited, for a house I only saw through an agent on FaceTime. I have no solid answer for why I’m the way I am. Why not?</p>

        <p>The synchronicities are coming back. I had a thought in the morning that I should watch <em>Little Miss Sunshine</em>. I had never watched that movie in my life and a thought like this had never occurred to me before, but for some reason the vision of the movie poster crossed my mind. Then, a few hours later, Halberstam, in the introduction of his book, goes into detail about the radical plot triumphs of <em>Little Miss Sunshine</em> as an example of queering the coiffed norms of pageant society. So then I had a beer and watched <em>Little Miss Sunshine</em> before bed. And I thought to myself how much I love this dance with the universe: first it shows me some curious pattern or vision or coincidence, and then I get to respond to it by nodding along, honoring it with my time.</p>

        <p>This is what I want next, actually, and much more of it: to honor curious, significant things with my time. Thích Thanh Từ said, “Whatever the tasks, do them slowly and with ease, in mindfulness. Don’t do any task in order to get it over with. Resolve to do each job in a relaxed way, with all your attention.” That’s some commitment talk if I ever heard it — full enmeshment with the present moment, delighting in the pleasure and pain and pauses of whatever is in front of you, wholeheartedly. In my last call with the Dorsia team, we talked about what I would do post-employment. I said I would dilly-dally and rest, but also work on my personal website, and take my time with it. I said something along the lines of, “there is something really rewarding about making something for myself, as if no one else exists.” Catie followed. “That’s quite beautiful. That sounds like something we should all write on our hearts,” she said. I didn’t have a reply for her lovely comment.</p>

        <p>I guess if I were to reflect on why I am such a high-commitment person, I would say something about how I’m aware that my life on Earth is impermanent. Nothing stays put forever, and nothing is perpetually ownable. Yet there must be a reason why my life continues to give me opportunities to try. It introduces me to people that I can choose to stick with while knowing that it’s not always going to be perfect, and there’s no guarantee they’ll be in my life forever. It enables me to make homes out of places even though I might be uprooted or, at best, they will go back to nature in due time. It’s only through these commitments I get a peek at just how seriously ephemeral life is. So, the process of striving for permanence in the face of this is a paradoxical yet rewarding journey. It’s disciplinary in that it requires me to define and pursue a goal that is challenging; it invokes positive thinking because once I’m locked into something, I have to make the best of it; and it’s often a social process of discovering my merits, talents, and values in the context of other people. I like to think I was given 80 years alive on Earth to practice the art of letting go, and the most time-effective way to do this is by jumping into projects, people, and places totally and fully and over and over again, immersing my body, wealth, and identity full send into these pursuits, and growing my love and appreciation for all of it until I’m so stuffed with memories of hard work, discovery, failure, and gratitude that I can move on without a fuss and release it all back to where it came from. I commit to things because I want to enrich myself in their pleasures <em>so that</em> I can let them go. Does this make any sense?</p>

        <p>I’m feeling my hibernation come to a natural close imminently, meaning I’m almost ready to embrace my renewed, ambitious, stern, and disciplined self. I have a lot of work to do and “me” to build. What do I want? I want to be an excellent writer, a lucid thinker, and a prolific strategist. I want to be powerful, symmetrical, and balanced. I want to be challenged. I want to delve into my crevices, explore my multi-armed nature, and commit to my angles, but stay silly, sweet, and tender-hearted. I want to be a rounded-corner star.</p>

        <p>The name of the members club I joined is “The Writer’s Room.” I think this is funny, suitable. Suitable with my Masters program in narrative studies and my design collective called Plot Twisters. Suitable with my thesis and website and life goals waiting to be typed up. Very suitable as I get back into personal reading and writing. And you know what? I live just down the block on a street called Literary Road. I can’t make this up. &nbsp;&#x273d;</p>

      </div>      

    </main>
  );
}