import Image from "next/image";
import Link from "next/link";
import entryStyles from "../../styles/entry.module.css";

export default function Page() {
  return (
    <main className={entryStyles.entryStyles}>
      <div className={entryStyles.writingTop}>
        <h2><Link href="/journal" className="breadcrumb">Jenny&rsquo;s Journal</Link>Pit Stop</h2>
      </div>
      
      <Image
        className={entryStyles.writingHero}
        src="/journal-graphics/pit-stop.jpg"
        alt="Project"
        width={2880}
        height={2025}
        style={{ width: '100%', height: 'auto' }}
        quality={100} 
        priority
      />

      <div className={entryStyles.heroCaption}>
        Back home in Renton, Wai Po presents me with the impressive onion bolt she’s growing in her plot of the community garden.
      </div>

      <div className={entryStyles.body}>
        <h1>Pit Stop</h1>
        <h6>August 2021</h6>
        <h6>1 min read</h6>
        <p>
        You would think no one is watching you in the suburbs
But every time i go home, people tell me they saw me walking

          good morning  the birds are singing brightly this morning in Renton, WA. it’s been really nice to be surrounded by trees and calm, crisp summer after spending the past year so far away from this weather. I got back here last Wednesday, so it’s been about a week of adjusting to the new timezone. I was in Doha, Qatar for 2 weeks before to pack up some clothes and rest a bit; before Doha I was in Kuala Lumpur in Malaysia staying with my extended family for a couple months.

Malaysia was a really touching experience. It was the first time I met my family on my stepdad Selva’s side, who grew up as an Indian Malaysian. I stayed with his younger sister Mano (my aunt) and her husband Jay (my uncle). I grew quite close to them. I discovered so much new food with them; we ate almost every meal at a food stall/food court. Malaysian food culture is similar to Thai food culture I imagine, so you probably know what I’m talking about. but the cuisine was incredible. A true fusion of ethnic spicy Malay food with Chinese influence, Indian influence, Thai, and Indonesian. It was like all the food I grew up eating but 200% more spicy. I think Malaysia is my food heaven.

While there I also traveled with my aunt/uncle, stepdad, and my mom who was also there briefly during my two months, to Penang, another city in Malaysia known for amazing food. I’ll attach some pictures shortly, but my favorite dish was a soup called assam lakhsa. Assam means sour, and it’s essentially a sour fish soup (very lemongrassy) with udon. unfortunately I still have my stomach sensitivity so every time I eat it I have a little reaction, but it’s so worth it. I also spent a good amount of time with my cousins and other aunts and uncles there on Selva’s side. They’re all also Indian Malaysian so I learned a lot about (south) Indian cooking, cricket, and celebrations. We hosted Tamil New Year while I was there, as well as a few birthday parties for my aunts and and my cousin Tej who turned 5. This spring was probably the first time in my life I’ve felt like a part of a big family; growing up it was mostly just my brother and me in our small house, and my mom who was pretty stressed out most of the time — a classic immigrant fam experience I guess. So it was really beautiful to feel a part of something big. The feeling is like a sense of belonging and security that I would be looked after. I noticed so much of my general anxiety diminished just being there. I felt so much more safe and confident. :)

For career-related updates, I also started a new job. I’ve been freelancing for a while as you know, and one of the companies I was freelancing for made me a really good ($$$) full-time offer to be their Lead Designer. They have been willing to be flexible with my chaotic nomadic life, Plot Twisters and all. I think I’ll stay involved for a few years because they provide me benefits and I feel like I’m learning a lot from my boss Jared (his fun fact is that he went to school with Mark Zuckerberg and was the 3rd designer at FB, his claim to fame being the person who launched the Like button lol. He’s also the COO of Raya the dating app if you know what that is lmao). anyway I don’t think I’ve been in spaces that really challenge and nurture my creative/technical skills, so Jared’s been really fun to work with and learn from. The company is in the hospitality tech space, and right now I’m designing their flagship app which allows you to book hard-to-book restaurants by putting down a minimum table spend. my job is remote but the company is headquartered in NY and Miami, so I’m looking forward to spending some time on the east coast at some point. It’s really interesting to be working with hospitality/restaurant folks on this, and there are fun perks like having offsite tastings and getting restaurant bookings at nice places in NY and Miami (Carbone???!), though I haven’t been in the country to enjoy them yet. 

For now, I’m in Renton for a few weeks until June 14, at which point I’m headed to Oxford for a couple weeks because Plot Twisters got accepted to exhibit at a conference there. I didn’t get into the grad program I applied to btw (which is expectable since it was a moonshot for my application/background hehe), but it did help me learn about some academic goals of mine anyway, and in short I was accepted to my Masters at University of Edinburgh this fall! I’m looking forward to my program, which is an interdisciplinary literature/sociology program called “Narrative Futures” which feels really perfect for me. I think it’ll be a good structure to steward all my writing on my theories and opinions! I’m planning on focusing on the theoretical aspects of ideas behind Plot Twisters: media/design studies, narrative theory, psychology, and storytelling. The degree will be part-time over 2-3 years (depending on my speediness), so I’ll be able to balance it with Plot Twisters and my job.

I’ll spend a few weeks in the Oxford/London, fly back to hang out in Chicago to explore and see some friends until early July, celebrate my mom’s and brother’s bday in mid July back in Renton, then finally fly out to Scotland on July 24. Before I start my Masters on Sept 12 (which I will be doing part-time over the next few years as I work my full-time job too), I also got into a really cool summer institute for an artist residency for 3 weeks :D It’s called the Diverse Intelligences Summer Institute and it’s hosted at St Andrews University. I’m going to continue working on Plot Twisters artwork stuff there, and hopefully meet some other artists/academics interested in theories about intelligence and human life. After the retreat I’ll relocate to Edinburgh until November, and I’m looking at living in a place like UpStart but for digital nomad/traveler types in Edinburgh while I balance part-time studies + working. I think it’ll be a fun way for me to meet people and be in a central location in the city. In November I’m heading to Doha to see a few games for the World Cup! I’ll be there through December, then probably back in the US for a bit. Not sure yet where I’ll be come 2023, but probably somewhere on the east coast or in Europe since those are the only timezones that work for balancing both US east coast-based work + UK-based school. I’d love to stay in Scotland year round but because I’m a part-time student, I’ll only be able to stay in the country on a visitor visa for 6 months or less at a time. So I’ll freedom to go anywhere for half of the year… maybe I’ll finally do the Spain stay I’ve been dreaming about for a while :) 

Plot Twisters overall has been really blossoming as a community, which I feel so grateful for. We have weekly hangouts on the weekend and a handful of us gather to discuss our work and research, watch relevant movies together, and talk about goals, healing, and life. We’re also making progress “professionally,” with this conference exhibition at Oxford coming up and we’re also hosting an online storytelling/writing contest with a nonprofit sometime in July and prepping for that. I’m doing lots of reading and learning from folks in the psychotherapy and media studies spaces as usual. Most of my time is spent managing the ideas of the group and making decisions about what to do next. It’s very creative and I feel thankful to have made a space for this part of myself. My full-time job can be pretty draining. I’m one of the only women making strategic product decisions, I’m the only non-white person on our 30 person team, and the leadership is all 15-20 years my senior and male, so I feel young and a bit out of place in comparison. Though being remote it’s more flexible than a 9-5, that kind of context-switching and self-moderating can be draining. These circumstances make me feel even more grateful for the Plot Twisters community, which is very diverse, queer, and sensitive to needs lol.

Outside of Plot Twisters folks, who I do talk to pretty much every day or every other day online/via calls (mostly about our shared interests and dreams lol), I haven’t been particularly social. The UK was fun but also stressful after Nick left; there were a lot of people and the drama felt like Hoover House but worse because everyone was blatantly sleeping with everyone else and the political takes were worse lol. I was kind of caught fielding people’s emotions. I made one really good friend there, Lumi, who is also now part of Plot Twisters but also just a cool person who’s also entering the design space and exploring her creative interests. I also have been keeping in touch with friends past and present through digital penpalship, not unlike communications like this super long text. Reserving my social energy for this kind of connection has been rewarding.

In Qatar I didn’t meet anyone my age and mostly hung out with Selva and my mom, but that was good because some old traumas I’ve associated with my mom began to untwist. I think I feel more at ease around her, and much better at taking and sorting her expectations and being my own person. And in Malaysia I continued to grow in that sort of “healing family wounds” kind of way, meeting my extended blended family and understanding the cultural values about how kids are raised and lives are managed. I also tried a form of therapy called “Internal Family Systems” mixed with Nonviolent Communication, recommended by Lumi. that’s been really helpful for me; it’s a practice that frames people as being made up of many subpersonalities or parts — and cast of internal family members — and guides us to speak to/learn from our parts in a kind way. It’s a fun tactical application of our mantra to “love yourself.” Instead of just “yourself,” it’s plural: “love yourselves”

Reflecting on my relationship with Nick has also been helpful. Throughout the spring I had been swinging back and forth between feeling like I didn’t give enough vs feeling like I didn’t receive enough. I’ve been able to rework that internal narrative and recognize that feeling safe and healthy in a close relationship isn’t transactional like that. In all I think I actually became more confident that I’m a lovable person lol, and that though I of course have ways I can grow, a lot of that growth must happen in relationships with people (and not in solitude, which I have historically tended toward). I’m really grateful to have known him and will continue rooting for him from wherever I am. Anyway, I have a sense that my life being so active and everywhere these days will allow me to meet and grow with many new kinds of people. I’m learning to be less confrontational and abrasive in general (more tolerant of the people close to me) — recognizing how stubborn and outspoken I can be — though also totally accepting and hugging those parts of myself too. I recently found the song “Strange Girl” by my favorite Laura Marling who you intro’d to me, and the themes of that song resonates with ~the wavelengths of my existence~ strongly these days hahaha.

Health-wise I’m doing quite well. I’ve totally conquered the disordered eating/excessive exercising, and I think my metabolism is healthy again. It makes sense that my physical health is tied to my mental health. anyway, most of my exercise is walking: I try to go on a few 30 min - 1 hour walks per day to just decompress and breathe fresh air. Since I’ve been in Renton I’ve also been doing hot yoga, but it’s a lot harder than I remember, so I’m taking it easy. Body dysmorphia is improved and I’m also doing things like taking vitamins and taking care of my skin and hair with ~nice products~. Since I’ve been staying with my parents for a while and then was in Malaysia eating out for every meal, food/cooking have been non-issues and I’ve been lucky to eat my mom’s Chinese cooking (while also learning from her some staple recipes I’ll be sure to bring to the UK when I’m there this fall). The only thing I’ve been skimping out on is my full 9 hours of sleep every night, getting more like 6-7 depending on the day. It was really bad when I was in Malaysia working east coast times for my job, bc I had to start work at 9pm at night. But I’ve been better at managing my priorities and setting time boundaries, and being in Seattle for the next few weeks it should all be more bearable.

I’m very excited for all the foreseen and unforeseen adventures on my plate in the coming years, though I will admit it’s been a bit tiring. I find myself fantasizing about planting roots, possibly investing in land for a farmhouse, and I’m reminded of your classic dream about running a farm. I’ve been spending a good chunk of my free time on Redfin just exploring homes, land costs, and options across the west coast — I do this enough that it’s become a sort of hobby lol — and I think investing in a place someday soon in WA, Oregon, or California would be so fun. Mano and Jay are immigrating from Malaysia to the USA in the next year or so, and my mom is also adopting some of my 16 year-old girl cousins from China so they can come to the US (long story short, they’ve had a hard life and have been neglected by their parents, so my mom wants them to move to the US and have me become a guardian if they do), so it’s been on my mind to get a place to have a home base for myself, my family, and my friends. Now that I have a job I might be able to afford a downpayment in the next handful of years, so I’m putting this farmhouse energy into the universe! don’t know if you’re still on this dream track, but maybe it’s in the cards one day to think about that SoCal farm community you had talked about back in Arroyo Grande!

Longer term, I think after learning from/working this job for a few years, building Plot Twisters, and finishing my Masters degree, I’d like to pursue my PhD. Applying to Oxford was really informative, and I realized that I’m not really a social scientist type. My work tends to be more creative/narrative-driven, though not in the art school realm either. Interdisciplinary literature programs that allow me to integrate psychology with social humanities research would be ideal, but of course, those are rare to come by (and extremely hard to get into when they do exist — there’s one at Stanford I am keen on but takes only 3 people out of 150 applicants every year!). I’m slowly combing through my ideas and getting a lay of the academic disciplinary land, so I’m hoping in 3 years I’ll massage my goals into a very clear vision for a 100k-word dissertation so I can get into a PhD program that will propel me further in my goals of creating nourishing technology, and one in which I’ll be happy. Anyway, I feel really happy to be where I am after a few years of such wandering and looking, so I look forward to taking my time getting to this next milestone.

As far as balancing living my dreams with my personal and social life, my work-life balance has been manageable though obviously I’m busier than the average person our age. I’m really grateful though and find myself excited to just be alive and able to explore so many cool paths. The friends I make and keep in touch with have been really supporting, and I don’t feel like anything is missing at all. As far as partnership-type intimate relationships, I feel good to release from desire/expectation of that after a year of living with Nick. I have had one dalliance since the breakup… with an older man… While I was in Oxford visiting my friend in the winter, I met up with some mutual friends of some folks I was living with and hit it off with one of them, a philosophy PhD student. He was significantly older than me lol but I liked him so I pursued it. I stayed with him for a few days and then returned to my life when I left Oxford. I’ve also had some long and longstanding phone calls and written exchanges with some other friends I’ve met in my adventures that I intuit have some interest in me. I guess that’s how Nick and I met, but I don’t think anything will really come from those and I’m not really interested in acting on them. Generally I don’t know what’s to come in my love life, but I’ll try to stay playful and open. Maybe this is funny, but I’ve noticed that my “type” (a type being a type of person who I tend to attract, which may or may not be the kind of person I actively pursue) is white (or non-white but pretty culturally white) men who are nerdy and kind of reserved, highly knowledgeable/educated in computer science or philosophy (or both lmao), have an extremely particular taste in music, are liberal in a democratic-establishment kind of way, meditate, have very specific bodyweight exercise routines they practice, and love to read (and/or write) about something niche, like veganism, self-help, or artificial intelligence in a way that relates to their philosophy interests lol. For some reason it seems I’m interesting to this kind of person! I think it’s something about the way our interests mesh… I guess I write this down as a goofy little observation. I project as I continue to pursue my own goals in academia and beyond, I’ll become increasingly surrounded by this kind of person, for better or for worse lol. The adventures ensue!!!

On that quirky note, I am grateful to spend this time sharing a snapshot of my life in writing. I’m eager to hear how you are, and how you and Boldo and Isaac are getting on. I expect you’ve been passing time in a fun and fulfilling way, and that sunny LA is still sunny! Honestly this decade has been pretty harrowing so far lol, but I hope you have wonderful and magical pockets of love in your personal life. Would love to know about your days, your martial arts practice, any adventures big and small. sending some early birthday love to ya from Washington. &nbsp;&#x273d;</p>

      </div>      

    </main>
  );
}