import EntryLayout from '../entry-layout';
import Image from 'next/image';
import entryStyles from "../../styles/entry.module.css";

export default function JournalEntryPage() {
      
  const heroImage = (
      <Image
        className={entryStyles.writingHero}
        src="/journal-graphics/staking-my-positions.jpg"
        alt="Project"
        width={2880}
        height={2025}
        style={{ width: '100%', height: 'auto' }}
        quality={100} 
        priority
      />
  )

  const heroCaption = "Taken on an early morning in a Cleveland coffee shop. I love skull art :)"

  return (
    <EntryLayout slug="staking-my-positions" heroImage={heroImage} heroCaption={heroCaption}>

        <p>I’m back in Cleveland after being in the UK for the last two months. Updates since returning to my life here: last week I walked to the men's barbershop down the street and impulsively asked for a bob. My car and a neighbor’s car got broken into on Wednesday night. Nothing taken, but I’m paying $200 to get my rear passenger window fixed. My new teammates at Dorsia have been nice to work alongside. I got a 2-year membership to the Cleveland Art Museum. Celebrated Sarah’s birthday party which was themed for Sofia Coppola’s <em>Marie Antoinette</em>. I started taking Ashwaganda, N-Acetyl-L-Cysteine, and B complex. Last night, it rained so hard that my ceiling started leaking, so I had to set up a bowl to catch the droplets. Our building is getting our roof fixed though, so it shouldn’t happen again. I noticed my eyesight getting worse from screen fatigue, so I’ve made it a point to spend time outside sitting in the park or going on a walk and looking into the distance. I have been spending free time window shopping for sofas online, but struck with indecision. I started using ChatGPT to help me code jenny.world. On Sunday I got two pothos plants. I’m sleeping okay, not great.</p>
        
        <p>Mostly, it's been a couple weeks of just doing things and things happening. I’m reading Shannon Vallor’s book <em>Technology and the Virtues: A Philosophical Guide to a Future Worth Wanting</em>. It's resonant and inspiring, but it also opens a sort of intellectual Pandora’s Box for me, so every handful of pages I start to get overwhelmed and have to take a break. I think it's because my personal sense of moral presence and truth has been a little elusive, so I want to take some time to see if I can write it out to the surface again.</p>

        <p>Today on the freeway, I saw a raccoon four lanes into a six-lane stretch. He or she had two more lanes to go to get fully across. It was perched on its hind legs with its arms in the air, and it looked terrified. It looked like it was trying to move when a car light would begin to illuminate its path ahead, but would stop short and shiver backward when the car would zip by.</p>
        
        <p>I first thought: wow, there’s really nothing for humans to do about this besides totally destroy our car ecosystem. I thought next about calling animal control and leaving it to them, but I wasn't confident they would get there in time as the raccoon was actively on the move in the middle of the freeway. I felt powerless. Then I thought: actually, a thing I could do to interfere is to exit and loop back onto this stretch of the freeway, drive slow in the lane I think the raccoon was in, and wait until I confront him or her and just stop in the middle of the lane with my hazards on, so I block all incoming traffic until the raccoon passed.</p>

        <p>I didn’t do this even though I had this thought, but it seemed like the virtuous thing to have done. If I were an excellent human, with excellent mastery of my agency in this world and our society, maybe that’s what I would do. That seems like the right solution, and the humane and whole path.</p>

        <p>Unfortunately, my lack of excellent agency led me to drive past and similarly breeze by all these thought exercises and considerations about the raccoon in just a few moments. I let my mind justify my actions: &ldquo;Even if this raccoon made it across this highway, it might not survive much longer anyway if it stays in this car-ridden city.&rdquo; Or, &ldquo;Even if I save this one raccoon, this could happen again to another raccoon next week, tomorrow, or in just another hour.&rdquo; An inner voice knew, though, that these justifications didn't really hold water for me because I don't value long-term logic or utilitarian calculations. I value the thing with the face, the miracle of creature, and an individual experience of life—and this particular raccoon was living a terrifying moment and I didn't defend him or her. I have felt pretty uncourageous and mediocre the rest of the day.</p>

        <p>When enough people are mediocre in this way, nihilism becomes more and more reasonable. I don’t know if that raccoon made it out alive tonight. I ruminate on how extremely sad and pathetic it is that, whether it did or did not, it wouldn't change the fact that other present and future raccoons will also be subject to the same miserable circumstances. Their lives and deaths are governed by poorly considered circumstances—in this case, the human reliance on cars—and this leads to generations of endless pain, challenge, and stress for raccoons and other forgotten subjects of this project.</p>

        <p>Moments like these bring me to the edge of my moral landscape, making me feel stuck between the futility of the systems we live in—the routines and unknowns that trap us in cycles of harm and meaninglessness—and the battle of life to persist and survive. I think of the raccoon, but also poor friends, disabled friends, disempowered friends, and myself in some rare contexts. These moments show how our world—and agents like me within it—is built around manmade laws, conveniences, and uncertainties that make the experience of the miracle imbalanced. Some life accepts and relaxes. Other life reaches, scurries, and hopes for safety. We rarely control which side we fall into.</p>

        <p>In this tension, sometimes I find myself paralyzed. I want to do the good thing—to align my actions with a sense of ethical responsibility—but I don't always do it, then I get in my head about whether the good thing is actually good. I feel like I rarely know enough. But I do act from a place of emotion</p>

        <p>I’m going to spend the next ten years digging through the literature, staking my positions, unearthing philosophical traditions and epistemologies that startle me, raising them back up to the ground to the realm of the sciences and psychology, gesture toward intuitions in this soil, research my hypotheses, and reach just conclusions about the narrative capacities of humans. I will argue for the deep truths and the reality of our needs in an aspiring technomoral society, and write many pieces to communicate these bits of wisdom to the masses. These will touch the philosophy of technology and the ethics of computing, as well as comment on design practices, creative expression, and the state of education. I will aggregate all of these curiosities and tested arguments into my augmented reality interfaces. The rhetoric of my technological and social vision will drive digital innovation, producing tools that will change the world. I will embark on operating one of the most elegant, efficient, nurturing, and healthy tech organizations on this planet, attracting some of the kindest, wisest, and whip-smart people alive.</p>

        <p>I am Jenny, and though I am currently 26 and chaotic, I plan to be in my 40s one day with a deep security in who I am and manifesting onto planet Earth what I have always expected to, since I was a child. I am level-headed, funny, joyful, and wise.</p>

        <p>I feel present with the people and motivations around me, and I feel at ease with aligning goals to action. I feel a deep gusto for my daily life, the mundane and the unique combined. I feel compassionate to who I have been at every age, even my nuisance years, and I feel happy to share and laugh about all my experiences.</p>

        <p>I act and make decisions with confidence in how they align with my expected outcomes. I protect my time and that of my loved ones and collaborators, though I am nice about parting advice to people who aren’t so confident or aware of social limits yet. I do only the things that contribute to my goals within two degrees of separation — so if not directly, than only slightly indirectly — to ensure that everything I do is using my time in the most delicious and meaningful way.</p>

        <p>I love my family, friends, and the life I get to live each day, even when my body feels funny or has stomachaches, even when my head feels groggy. I love walking, eating, resting, and laughing. I love to take care of the people closest to me, making them feel heard and seen and encouraging them to be the best selves they can. I love to be taken care of, too, by my loved ones and my community. I love sharing my voice and experiencing the resonance that others feel when they hear it, and inspiring them to share their voices too.</p>

        <p>I speak my messages about love, human life, digital life, creation, and growth with targeted accuracy and brevity. I don’t elongate my messages unnecessarily: I speak to inform as many people as possible, conveying what I understand to be complex ideas in the most elegant way I can. I strive to pare down complex ideas before I speak, and only speak when the rhetoric feels logical and natural. I speak the truth about myself, owning up to my mistakes or oversights, but I also speak the truth about situations at hand, including others’ direct or indirect misjudgments, wrongdoings, or offenses. I speak with a command on language: I communicate with sternness when a topic is serious and challenging, and admonishment when discomfort is caused by transgressing social or personal limits. I take a moment to identify what the transgressions are, what needs are not being met, and what possible solutions or avenues of healing could be, all before I speak, or as much as possible before I speak. I understand these may all be evolved through conversation with other people, but I give myself the patient beat to analyze a situation before I speak about it. I am kind with my words and expressive of my emotions. I let my heart guide my message and use my brain to assign the best language units, or other mediums, to communicate it. I speak with firmness, confidence, and authenticity, and people know to trust what I say.</p>

        <p>I see a joyful life with lots of hard work ahead. I see leveraging my digital tools efficiently to get all my projects done in a timely fashion, and I see mundane yet scrumptious activities — chores, money management, moving furniture, stretching — interspersed between the vision building. I see myself learning physical attunement again and accessing the infrequently visited tendrils of my body. I see love, breaking down projections and anxious self-narratives, and good food and fun, full days. I see bright colors in nature, beautiful homes, the smiles of people I love, conference rooms, clothing that fits my body just right and feels comfortable to wear all day, and road trips with my team. I see many teams, and I see myself being central to all of them. I see my posture improving and personal growth. I see getting into a dream university, with accolades and without funding issues.</p>

        <p>I understand that time is a resource to be enjoyed, and that my body is the frontier of that adventure. I understand that I need to be patient with myself and my environment, so I can time my actions to their milieu and execute on my ambitions with blessed and deliberate timing. I understand that I need to be consistent with my material care, including physical self-care, wealth management, and relationship care. I understand that I’m on a journey to find my best routine for these activities, in balance with achieving my loftier humanitarian dreams, and that I will do all of it, it’s a matter of patience, timing, and artful use of energy. I understand that I am still governed by anxious and faulty self-narratives, and maybe these will evolve and maybe they won’t, but I need to keep them in check as I indulge my time every day, because they do have the ability to overtake me in some moments. I understand that I am in full control of what I choose, and that life is a multidimensional tapestry of nested realities that I can lean in and out of at will. I understand that I will always be the same even as I change because I’m the witness to this story and not an incidental character, and I am excited for how the whole work comes together in this lifetime and beyond. I understand that love is the governing force of the reality I want to live in, so I will keep tuning into it in my body and heart for as long as I’m on this planet. I understand that it’s my job to share this with as many others as I can, too.</p>

        <p>“Every word is a hypothesis and a test—while recognizing fearfully that with even </p>the most casual remark we are building ourselves and our world irrevocably.” - nathan schneider

        <p>I had this moment of doubt today that I’m going down the wrong hole by pursuing academia and reading all of this about the philosophy of narrative, technology, and computing, and that building the tools of my dreams have nothing to do with any of this, and I could literally try starting the creative process now. However, after some brief reflection, literally like 30 minutes, I realized that it’s a choice to limit myself in this way: of course I could build something today right now, but the quality of it will change and be shaped by the particular process I follow, which will be tinted by the stubbornness and types of processes I inhabit today, as well as the people I decide to engage with as I conceptualize and test the work. Meanwhile, if I go down these philosophical paths and really unearth a deep understanding of knowledge traditions and how they can be contextualized today, I’ll have awakened a new cognitive and spiritual path for myself and my personal epistemologies, and because the tools I want to create are all about perception, I’ll have accessed a new part of me that will inform the tools I make, if not directly expressed, than indirectly in the tacit wisdom that comes with such exploration. This wisdom will inform my decision making and make me a more conscientious and thoughtful creator in some way, though that particular way won’t become apparent to me until I reach that point.</p>
        
        <p>In this way, I shouldn’t lose hope that what I create will be dislodged and estranged from my philosophical interests today. Though steps in the process may seem like that, if there’s anything I’ve learned while creating Plot Twisters, it’s that the creative intuitions always come back and manifest in even more crystal forms than when they were first revealed. The energy, when it’s coming from the right and same and consistent place, will always have the same qualities, and it will pick up whatever nuances it gathers from the contexts it’s funneled through.</p>
        
        <p>At the very least, Jenny, you should expect that your ultimate tools will be very thought out, attuned to the abstract, and deeply humanist, because that is where you are letting your energy travel now. It will pick up what it loves in these spaces now, and down the line, those curiosities will reappear in new forms and find themselves reflected in any future creations.</p>

        <p>Don’t worry so much, and don’t doubt yourself. &nbsp;&#x273d;</p>

        </EntryLayout>
  );
}