"use client";

import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import Image from 'next/image';
import Link from 'next/link';
import entryStyles from "../../styles/entry.module.css";
import Breadcrumbs from '../../components/Breadcrumbs';

export default function Page() {
  const [entry, setEntry] = useState(null);

  useEffect(() => {
    fetch('/data/journal.json')
      .then((response) => response.json())
      .then((data) => {
        const foundEntry = data.find(item => item.writingSlug === "jenny-jny");
        setEntry(foundEntry);
      })
      .catch((error) => console.error('Error fetching journal entry:', error));
  }, []);

  // If entry is not found or still loading
  if (!entry) return <div>Loading...</div>;

  return (
    <main className={entryStyles.entryStyles}>
      
      <Breadcrumbs>
        <Link href="/journal">Jenny’s Journal</Link>
        <span>{entry.writingName}</span>
      </Breadcrumbs>
      
      <Image
        className={entryStyles.writingHero}
        src="/journal-graphics/jet-lag-jenny.jpg"
        alt="Project"
        width={2880}
        height={2025}
        style={{ width: '100%', height: 'auto' }}
        quality={100} 
        priority
      />

      <div className={entryStyles.heroCaption}>
        The flower-littered balcony of my flat in Bayswater near Hyde Park in central London.
      </div>

      <div className={entryStyles.body}>
        <h1>{entry.writingName}</h1>
        <p className={entryStyles.descText}>{entry.writingDesc}</p>
        <h6>{entry.date}</h6>
        <h6>{entry.readTime}</h6>

        <p>Growing up, I was raised by several different people and environments. I was born in Arizona, but my mom and birth dad were both new immigrants on welfare who couldn’t afford to take care of me. At six months, I was put on a plane to China, to stay with my mom’s parents in Shenzhen. I lived there with my grandparents until I was 5. I learned to speak and write in Mandarin, which was my first language. Back in the states, my mom and dad separated in my absence.

At age 5, I came back to live in Washington state with her and a man who soon became my stepdad. I knew no English and I was very scared and shy. She worked three jobs and invested all her income on my attendance at a Montessori school so I could learn English without being bullied and develop a curiosity for the world in a safe environment. My mom also paid for ballet classes, soccer, gymnastics, acting lessons, and art classes for me to break me out of my shell. Though she was always busy and stressed with work, paying for my unique education and hobbies is how she showed me love. And she showed me so much of it: she created as many opportunities as she had in her power for me to follow my curiosities—every possible cookie trail—and grow.

I remember crying every day at first, but soon I began to pick up the language. Kind teachers met me where I was and encouraged my creativity. Slowly, I began to appreciate my new environment, and even dreamt about maybe one day decorating my own classroom, teaching my own students. When I was 7, I vividly remember drawing maps of the world as I saw it in my mind. I called my world the “Jenelan Islands.” Looking back, this was my earliest creative intuition. I consider this the beginning of the Plot Twisters cookie trail in my life.

When I was 10, my parents lost their jobs so my younger half-brother and I both transferred to a new school. I lost touch with friends, was bullied, and encountered the experience of being graded for the first time in my life. Through all of these changes, I coped by reading more books—I especially loved classic fairytales, stories from other time periods, science fiction, and myths from different cultures—and spending more time on the family computer.

Online, I explored game worlds like Neopets, Maplestory, Webkinz, Wizard101, Toontown, Club Penguin, Fantage, Poptropica, and Millsberry. They invigorated my imagination and creative intuition. I found forums and met inspiring friends through Twitter, some of whom I still talk with today. I created digital art, tutorials, and stories about my favorite worlds for myself and other people, which eventually evolved into my current skills as a graphic designer and illustrator. By age 12, I learned HTML, CSS, and JavaScript so I could build websites to share my thoughts and artwork in one place, publicly. I still blush to share this, but my first blog and art portfolio from when I was 12 was called imaJENation, which I hosted on imajenation.net (clearly, I have always loved words and wordplay—another cookie trail I have indulged in!). I eventually accepted the dreadfulness of school and made new friends, but my digital hobbies were how I stayed creatively engaged. I continued to assemble a series of websites where I shared my photography, digital artwork, fonts I designed, Photoshop brushes I created, and blog writings about my daily life.

Over the next few years, I changed public schools 3 more times because my family moved around. At each school, I noticed a different set of rules: pass-fail grading, BAME scales, Common Core power standards, and the traditional A–F system. I compared each environment to the freedom and creativity I experienced online, and I realized just how stifling these curriculums were. Disillusionment hits hard when you’re 12, and kind teachers were few and far between. In class, I watched my friends lose curiosity in every subject, and all the grade points and numbers grew increasingly meaningless to me. It was like I was looking at my school life as a narrator, watching myself face more hoops to jump through and different, impersonal expectations to meet with each year. Through all of these transitions, at least I knew I could always explore myself through my creations after school, digitally. Online, I felt like I could actually grow; I could follow my cookie trails instead of a cookie cutter. As I explored these curiosities, I felt a sense of flow: free, at peace, and honest with myself.

When I was 13, I took an opportunity to begin tutoring students at the local elementary school. I loved it. Spending time with younger students inspired my childhood curiosity for the world in a social setting, in the same way as my internet explorations did for me online. I discovered that my work as a tutor wasn’t actually about getting a student to understand a topic. My work was about encouraging them to be curious enough to try: if they would just be curious enough to try, I knew they could certainly do the rest of the work. I encouraged their curiosity by making as many connections as possible between their personal lives and the subject at hand. My work was to get to know them, and it was so, so fun.

Just a few weeks into tutoring, I had invented different and exciting worlds with these students to reframe their homework. I distinctly remember a girl named Anastasia who loved to talk to me about horses instead of doing her multiplication tables. I ended up drawing an imaginary ranch of all her horses on a grid, labeled by name, and used that as a map of the multiplication tables. There was another student with whom I imagined numbers as houses in a neighborhood, in order to explain long division. I recall drawing piles of mangoes on whiteboards and inventing songs for the parts of the water cycle. Creating these worlds with these students reminded me of my “Jenelan Islands” from my early education, and how I loved to learn, too. Even though these students and I felt restrained by our public school experiences, I recognized this as the system’s fault, not ours. We had discovered other ways make sense of the world, and I was very happy during this time in my life because I felt fully like who I was supposed to be. I had been exploring my own imagination style with online technologies for several years at this point, and my experiences as a tutor filled me with certainty that education could still be curious, playful, and personally valuable. I had hope that a better, creative learning experience could exist for every young person.

During the winter break of 8th grade, my hope inspired a vision. I had an intuition to combine my digital and educational passions to create an online game world that could make learning personal and fun. I drew a map of a planet, much like the Neopets map, that contained the “Math Mountains” and “River of Science,” guided by my earliest creative intuitions, inspired by many of the metaphors I created with the students I tutored, and motivated by my own understanding of learning as a joyful, personal process.

I iterated on the map, but still, the vision felt incomplete. How could I create a game experience that would inspire a person’s individual curiosity to learn, without being there to listen and talk to them in person like a tutor? I created several websites previously, but this was the project I cared most about, the one that would be the most difficult to build, the one I was most fearful of messing up. Most importantly, this is the one I knew most needed to be real. This project was not yet named Plot Twisters back then when I was 13, but it was and still is all of those things to me: the vision that I love, fear, and truly and deeply believe in.

I thought about it every day for my last four months of middle school. I tutored, then drew maps of my ideas; I went to soccer practice, then played with 3D game engines. In between it all, I tried to connect the dots between my daily to-do list and achieving my dream of making learning a fun and personal adventure online. I knew I was missing a lot, but I figured it was a matter of having enough time to explore my intuitions and follow the cookie trail.

Then, I entered high school.

Though I previously had time for this dream because school had not been so challenging, grades soon became harder and harder to earn. Precalculus was difficult for me to wrap my head around and biology was taught so strictly and unintuitively to me. Declining grades, lack of environmental consistency, and family financial strain led me to prioritize just getting through the school system by traditional definitions of success. I needed to go to a good college on a scholarship to alleviate the stress on my family. I needed to take initiative for my own future because my mom invested so much in me growing up. I began to see my vision as a waste of time because I could not yet output anything specific. I accepted the cookie the cutter. With so many other obligations now, I spent less and less time on this dream until one day, it was a vague idea I only used to know. Looking back, abandoning my intuition caused a lot of personal sadness that I never knew how to articulate for the next 7 years of my life. These feelings lasted until I reapproached the dream in Fall 2018.

I often think about high school and much of college in third-person. For 7 years, I put so much mental distance between my daily to-do list and my childhood dream until I fully lost conscious sight of that cookie trail. I felt like I had no honest goal because I never fully felt like myself. I felt like I was just coping with my day, most of the time. However, looking back, it is so obvious that my intuitive curiosity was still there, I had just tried to suppress it.

Throughout high school, my mom and stepdad officialized a divorce, my brother grew reserved, and I felt increasingly alone, anxious, and numb most days. Especially with my parents’ separation, financial pressure increased. I had to be excellent enough for scholarship money. Still, with this external goal in mind, bits and pieces of my visions and dreams came out: I had unintentionally taken my creative energy and made it fit into the cookie cutter. For example, I studied for my history exams by creating maps and timelines to help me understand continuities; I paired song lyrics with books I read for my English classes so I could more closely analyze the stories. As I sought out ways to prepare for college, my creative intuition about world-building, learning, and technology came out in disjointed situations: I mentored younger students, designed websites and graphics for my clubs, and created art for the school. I also found new activities that I would later realize influenced what Plot Twisters would come to include: organizing events in my town, learning about plants as a wetlands volunteer, writing newsletters for my community, speechmaking, and computing. Though I was really just looking to build my resume, business clubs helped me gain confidence in leading teams of people, and theater and improv acting introduced me to the infinite varieties of the world-building and the infinite importance of “yes, and.” Through recent years, I discovered the value of each of these experiences to my work with Plot Twisters and beyond. Because of this, I have learned to never carry regrets for my decisions. I convince myself to trust that I am always on a journey, even when I feel a lot of personal sadness or confusion about what that journey is. There is always more to pay attention to and unravel—if not now, then tomorrow.

As college applications loomed closer, I constantly worried. Who am I? What do I want to be? Internet geek? Designer with interests in systems? Future business leader? Creative tutor? Writer? Artist?  I didn’t know the answer. I had few mentors and adults to seek advice from, and knew no role models for what I was actually interested in, because I myself could no longer articulate what I was actually interested in. I had lost conscious sight of that old cookie trail from long ago.

During this time, I had written in a notebook a list of all of the careers I was considering. I wrote: “I don’t know what I will choose for college. I want to be so many things. I want to be a graphic designer, a teacher, a computer scientist, a children’s book illustrator, an education reformer, a journalist, a web designer, and a creative writer. I want to pursue all of these careers so I can create things that I care about. I want to care about what I am doing, and I want to remind other people that they should care, too.” Again, it is so obvious looking back that I have always known what I cared about, even when I wasn’t consciously working toward it. The intersection of all of these careers so easily give it away in hindsight, but at the time, I felt very lost. Every now and then, I look through this notebook and remind myself to trust my feelings, especially when I have doubts about Plot Twisters, which is more often than you might believe. I wish I could tell my teenage self right now that she, in her 20s, will be well on her way back to her childhood dreams, with so much love for her daily tasks, practicing each of these hats with a team of the coolest people in the world. I can see the image of setting my backpack down after school every day, feeling tired, confused, and vaguely sad.

With no guidance and these disjointed intuitions in my pocket, I applied to a random array of schools for art, computer science, communications, political science, and business. Looking back, I gave these applications my best shot, considering how far I had strayed from feeling like my happiest, creative self. 

Days before the deadline, I found one program that combined many of my interests: a school at the University of Southern California for the “Arts, Technology, and Business of Innovation.” I was so curious: this was the first application where I didn’t have to choose one hat, or one curiosity to show off. I could simply bring them all. I wrote about all of my intuitions in those essays, and for the first time in a long time, I felt a sense of flow. The last part of the application was a 1-minute pitch of “an innovative idea.” Just a few hours before the deadline, I remembered that old intuition in the bottom of my pocket. I pulled out this dusty idea about an online game world for education, along with memories of the “Jenelan Islands,” my early online websites, and all those elementary school students. For my proposal video, I quickly drew and animated the vision I forgot that I cared so much about. In those hours, I felt truly free, at peace, and honest with myself. When I got into the school on a scholarship, it felt like a stroke of fate, of God, of miracle, nature, magic. I immediately accepted.

Unfortunately, most of college felt similarly to high school: like a blurry series of disjointed explorations. When I arrived to study the “Arts, Technology, and Business of Innovation,” I was overwhelmed by how much talent surrounded me. I lost confidence in myself, and I lost my vision. I struggled through classes in computing, pitch-making, entrepreneurship, and accounting. I was exhausted by all of these changes. I coped like I did when I transferred schools at age 10: I immersed myself in novels. I took English classes unrelated to my major. I soon found myself writing about my life again, like I used to when I was young.

I started a blog, jennytypes.com, as a first step of creative reclamation. This website was a redux of imajenation.net. Then I declared an English minor, so I could have an excuse to indulge in narrative. My favorite classes were in the English department. My work with narrative felt disconnected from my intuitions in education, design, world-building, and technology, but I could feel that something was aligning.

I coped the best I could for several years. My daily to-do list never felt completely aligned—I was never doing exactly what I cared about—but looking back, it’s clear that my bits and pieces of my dream emerged, like it did in high school. I improved my design and coding abilities through my required courses and the startup community on campus. As I wore the hat of the digital strategist, user experience researcher, and user interface designer, I felt like my daily design practices were helping me toward something. I began mentoring design students in college and led branding workshops for high school students. I tried new hats that I was drawn to: I worked as a student journalist for a virtual reality lab, then at Al Jazeera as an intern. I conducted product ethnographies in various industries and met many interesting people. And I had a long while Though these still felt like the disjointed intuitions I pursued in high school, again, I have no regrets because they helped me build a community and regain confidence.

I took a class called “The Founder’s Dilemma,” which posed the idea that a startup founder fell somewhere on the spectrum of wanting to be “rich” or “king.” I never thought at the time that I would start my own company, so I didn’t think too hard about it. But somehow, this dichotomy didn’t sit right with me. Not all creators are want to be wealthy, or in complete control. Mothers, for example. I reflected on my own mother, who believed her job was simply to do everything in her power to create opportunities for me to grow. I remember thinking, “I would only start a company if I actually cared about the idea. I don’t know if getting rich or staying in power forever should be the priority. I would just want to do what’s best for the idea. I would want to be a vessel for something I care about.”

My internship before senior year was at Adobe as a User Experience Designer. On paper, this was the dream. I taught myself Toward the end of the internship, I tried to find other teams to join instead.

Again, here I was rummaging through my pocket of disjointed intuitions. I could list them, all the themes I cared about and thought were awesome, cool, or at the very least, curious. The obvious ones? Design, technology, teaching, mentoring, writing narrative, interviewing. Then there were the less obvious intuitions, the ones I had no idea how to place. Outer space, cybernetics, urban design. Motherhood, love, social systems, poetry. Community retreats. Improv. Love for retro graphics. Data visualization. Map-making. 

When I showed up to this empty lot, I didn’t know exactly what I was making, nor the question I was seeking to answer. All I knew was what I could visualize in my heart and mind, and one truth: to build the vision I care the most about—the one that I love, fear, and truly and deeply believe in—I needed to bring as much of my true self as possible. I needed to empty my pocket of intuitions and mix it all together into one recipe.

I thought about many permutations. At first, I intended for Plot Twisters to simply be a worksheet company. But I realized, printmaking wasn’t in my pocket. But I had digital design and web design. So I pivoted. I needed to do what I could easily put on my to-do list. I needed to turn my intuition into action. I thought about what other intuitions I had that I could bring. Map-making? I’ll make a map.

My creative intuition knew that I needed more people, and more experiences. I would not get anywhere if I just sat at my computer alone and kept attempting. So I forced myself to embrace the spice of life and take intentional, diverse action that I believed would make me smarter and wiser to build Plot Twisters. I got a part-time job as a strategist at verynice, a part-time job as a retail associate at Anthropologie, picked up freelance projects to earn money, and enrolled in Dutch classes and boxing lessons to invest that money, with the hope that these mental and physical learning adventures would inspire Plot Twisters. I reached out to contacts near and far, seeking their “Gift of Knowledge” for product insight. All the while, I saved whatever money I had so I could eventually support a small part-time team. At the end of each day, I asked myself, “What am I actually trying to build? What kind of founder am I?”

That year, the metaphors came together slowly. The metaphor of personal “Gifts” arrived I was working retail at Anthropologie last fall, packaging gifts for customers at cash wrap. Hats came when I edited an organizational strategy toolkit at verynice. At verynice, I also developed a deep understanding for the dynamics of a workshop, how to communicate lofty ideas, and the inner workings of a remote studio business, which all influence how I approach Plot Twisters as a studio today. On the weekends, I volunteered at Changeist. With 12 middle and high school students, I explored Los Angeles on foot and talked through long conversations about identity, during which we all laughed and cried. I tutored every Monday and Thursday, after drawing my maps and attempting my worksheets, at the local library, where I would count coins with Jacob and read with Monalisa. I encountered the idea of combinatorial play from my boxing lessons, where our combination drills taught me to perfect my form. I thought, “what if self-reflection was a muscle? What if we were making a self-reflection gym?” This was in Fall 2019.

I talked about cookie trails to folks in my artist collective house, parents I met on the internet, the leadership at local youth organizations in Los Angeles, the siblings of my friends, entrepreneurship incubators, and many others, in both planned and spontaneous conversations, in any chance I got. Some people were very excited, which made me feel like tomorrow was another day worth holding onto this intuition. Others didn’t understand me at all, which made me feel very insecure and crazy, like I was wasting my time. The voice in my head would say, “You should have stayed at Adobe. You should have kept your head down and went into a nice job. You should have listened to your mom. This isn’t making an impact.” I felt all these insecurities because, to me, I was 13 years-old again, scared and shy, iterating on naive maps and slowly putting the cookie trail together on my own.

I almost aborted Plot Twisters many, many times. I was so incredibly busy all the time: I worked these jobs, freelanced, tutored, volunteered, practiced Dutch and boxing, designed and redesigned the Plot Twisters website, developed the first Think Tank, met with local educators, and came home to write and reflect on it all. Soon, my lifestyle took a toll on my health. In December, I was a paralyzed by several ulcers during the holidays. In January, I got news that I had a tumor marker in my blood, meaning there was a potential that my body had cancer. My parents told me I had to take a break, and that no intuition was worth betraying my body’s intuition. They were right, so for several months I retreated into a quieter role. I relinquished most of my obligations and only focused on interviewing remotely, writing and reading for the Think Tank and processing all that I had been through all year.

I almost aborted Plot Twisters, but I didn’t. I didn’t because I remembered who I was healing for. I needed to defend that 13 year-old girl who wanted more than anything for this vision to come to life. I was reclaiming my creative intuitions for myself, for her.

I see so much of myself in Plot Twisters. From my old daydreams about how I would decorate my classroom if I were a teacher one day, . Even in my errands I’m working on Plot Twisters. For example, when other people go grocery shopping, they simply go grocery shopping. When I go grocery shopping, I look at the labeling and fonts on the products I buy, to understand what makes it so classic and accessible, to understand what features I might bring back to Plot Twisters.

I thought about it every day for the last six months of the pandemic. I read design books, then drew my ideas; I studied narrative building, then played with Notion. In between it all, I tried to connect the dots between my daily to-do list and achieving my dream of making learning a fun and personal adventure. I knew I was missing a lot, but I figured it was a matter of having enough time to explore my intuitions and follow the cookie trail.

I believe all intuitions are meant to result in some action. In other words, we have to connect our feelings to the activities on our to-do lists. Feelings and intuitions are not meaningless—we must make them meaningful in our daily lives. To me, this is journey building. If we feel, it means there is something for us to do about it. We have a responsibility to our feelings: we have the ability to respond to them. This is why ignoring my oldest intuitions about world-building and education technology made me feel a lot of sadness and numbness for 7 years. I wasn’t just ignoring my creative wits: I was ignoring my most basic intuitions of what I cared about. I was ignoring my feelings.

In the last six months, I’ve come a long way to understanding my feelings. Feelings are hard to understand, but I think I’ve finally started to grow up. Since this soccer team formed, the best intuition I’ve discerned in my body is that every person is a storyteller. This began as a little hunch long ago, but today I feel it with my full body. What can I do on my to-do list about this feeling? I looked around me for signs. I had a feeling that everyone was a storyteller, and I started noticing others in the studio feel like they were simply tagging along on my project. There was a lack of ownership, or feeling of belonging. This is the cookie trail. I paid attention to the feeling in me, then I paid attention to its signs around me. The action I will take to serve this feeling is to take a step back. If I truly believe and intuit that every person is a storyteller, I must do everything in my power to respond to the feeling, and make it real.

Every person tells their stories in different ways: some of us tell stories by writing, some of us tell stories by cooking. You might tell stories by drawing illustrations, by singing, or just by consistently being there for your loved ones. Whatever your way, each of us has many stories to share with the world. Everyone is a storyteller.

Today, I hope I made obvious the kind of founder I am. I neither want to be rich nor king. I just want to tell my stories. I tell my stories by creating metaphors to visualize curious new worlds for myself and others to share. To make money, I tell other people’s stories by creating brands and app interfaces as a freelancer. But Plot Twisters, for me, is my own story about all my childhood fears, worries, and plot twists. Plot Twisters is about sharing all those intuitions that I’ve kept in my pocket over my journey so far. Creating Plot Twisters is how I tell my story, for myself, for my creative healing. And I’m lucky and proud to find how my story could be useful to other people: I can answer that neighborhood question, “How might we inspire young people to experience learning as a curious, lifelong adventure?”

Plot Twisters is my first story, home, and baby. I will always care about it, think about it, and come back to it. To be honest, it hurts very much to put distance between myself and what I consider to be my personal creative healing, because I’ve put that distance before, for 7 long years, until I almost forgot about it, until the sadness nearly numbed. I never want to do that again. I would grow older, but I feel like I can’t properly “grow up” and heal if I didn’t see Plot Twisters through. Working on Plot Twisters full-time every day for the last six months was the happiest time in my life in a long time, in spite of how the rest of the world looked.

I have shown Plot Twisters my highest form of love by creating as many opportunities as I had in my power for this team to grow. I earned money so at least a small portion of the burden of contributing to this house could be financially alleviated. I will continue to give everything that I can, if you want me to. I have no regrets. 

I deeply understand my own process of learning as an infinite game—a curious, lifelong adventure. In reality, I have grown up since this childhood vision, and I do have other dreams and pending intuitions, too. But first, I am fully committed to seeing Plot Twisters through, however long it takes. I’m not building this home just because it’s what I want to do today. I’m building this home for a 5 year-old who came to a new country with not a lick of the language. A 7 year-old who drew and wanted to live in her maps, then a 10 year-old who didn’t know how to adjust to her new school. A 12 year-old who began to see through the meaning of grades, and a 15 year-old who pushed through the pressure of getting into college. Finally, the 21 year-old who finally—after so much rummaging to finally recover these plot twists—found her oldest intuition and is trying her best to see it through. As you can see, there are so many younger people I need to heal first, before I’m ready to fully move onto my next adventure.

I would continue to work on Plot Twisters full-time every day if I believed it was the best thing right now for the studio. But, for this season, I understand that other people need space to come to their own meanings and shapes of these words. It’s important for my home to become yours, too, if you intend to stay and build it with me. Plot Twisters deserves that from you. Of course, if you end up realizing Plot Twisters isn’t your home, this neighborhood is an infinite canvas with many other houses to explore and empty lots for your own creation. If you are here to stay, though, it’s your responsibility to understand what will make this feel like a home to you. I shared with you what I want from Plot Twisters. Now, it’s your turn. What’s your journey? Where’s it going? I will come back when you can tell me this with as much clarity as I have shared with you. I will come back to sing with you when you know your voice, too. Then we will embrace this vibrant and messy adventure, together.

Even when I’m not working on Plot Twisters full-time, I feel like I am, because my life journey is a part of the journey of Plot Twisters. I identify so much with it, even down to its silly name. What I’ve started in this empty lot is my home, but this can be your home too. I invited you here, after all. And I’m sure you have people to heal, too, past, present, and future. All I ask is for you to remember and respect what was here when you first arrived, compared to what was here when I first arrived. I nurtured it alone for years before you came. And if you were to leave, I would continue building this house alone, just as I‘ve always done. Only stay if you can find a piece that you would nurture even if no one else were here, as if you had shown up to an empty lot, too. Only stay if you can give Plot Twisters your clearest voice, love, and care, too. Remember that this is a home to heal for so many people.

Please keep it safe for me. I will do the same for you.</p>

        <p>Sending my love,</p>

        <p>Jet Lag Jenny &nbsp;&#x273d;</p>

      </div>      

    </main>
  );
}