import Image from "next/image";
import Link from "next/link";
import entryStyles from "../../styles/entry.module.css";

export default function Page() {
  return (
    <main className={entryStyles.entryStyles}>
      <div className={entryStyles.writingTop}>
        <h2><span className="subnav"><Link href="/journal" className="breadcrumb">Jenny&rsquo;s Journal</Link>Every Love Is Different</span></h2>
      </div>
      
      <Image
        className={entryStyles.writingHero}
        src="/journal-graphics/every-love-is-different.jpg"
        alt="Project"
        width={2880}
        height={2025}
        style={{ width: '100%', height: 'auto' }}
        quality={100} 
        priority
      />

      <div className={entryStyles.heroCaption}>
        Looking out from Calton Hill in Edinburgh, Scotland.
      </div>

      <div className={entryStyles.body}>
        <h1>Every Love Is Different</h1>
        <h6>October 2022</h6>
        <h6>2 min read</h6>
        <p>I'm currently in a walkable city with a nice income, which means on I can end my morning strolls by trying a different local cafe each weekend — and I don't have to be so cheap about it. My routine includes seeing smiling and busy people in the street, or at crosswalks, or in the park with their dogs, then reviewing menus in coffee shop windows to decide whether or not a dirty chai latte is one of the ways I will show myself love today. Where I stay in Abbeyhill is lined with some great Italian delicatessens, plant-based bakeries, and homemade takeaway stops. I begin my days with a cardamom bun when possible, and always stop for matcha if I find it. I get the "daily soups" even when they cost £8. My boots are finally breaking in.</p>

        <p>A year of mottled circumstances has passed since I last told someone I was based out of this time zone. Blackpool, Manchester, Doha, Dubai, Kuala Lumpur, George Town, Renton, Oxford, London, Lisbon, Chicago, St Andrews, Amsterdam, Edinburgh. It doesn't seem to matter whether I spent a few moments in a city or several long months. The temporariness of my stations, which I had to confront every time I thought about which of my present routines were lifelong or conditional, prompted me to treasure where I was and what I was dealing with — no matter how strange or awful — at least once a day. A few standout moments include the hysterical disbelief of finding the bed bugs in Manchester, my mom haggling expertly at the crowded gold souk in Dubai, and the vegetarian feast on Tamil New Year. I appreciate the cities and the people I got to know better in them; I loved laughing with Lumi as she barged into our Oxford Airbnb proudly hoisting a massive watermelon, and dancing on West Sands Beach until the night finally killed the bonfire. I remember my nerves, but also the times I was remarkably cool-headed. I keep the stories and the playlists, the jokes and the gifts, and that mindful saying, "Wherever you go, there you are." These have been pretty meaningful seasons.</p>

        <p>Starting my Masters has been ambitious, but great. I'm still getting used to managing full-time work with the reading and writing deadlines, as well as those burns of momentary embarrassment whenever I say something unduly strained in class because God knows how long it's been since I've been around this many new people. Nonetheless, it's kind of nice to be one of many in a cohort again; the university environment is stimulating and youthful. I feel especially grateful to have faculty stewardship in my interests in narrative theory and the future of technology. I'm coming to my own words for describing narrative: narrative is what is born from the sequence of fragmented experiences, whether presented in words, in images, or in the passing of life events through time. It's the melding of some given order of information units and the patterns we make between them. It's both the dots and their invisible lines, both the positive and negative space. This interests me because I see how all narrative mediums enable play because they prompt people to build upon and cite past or imagined instances of a phenomenon to enact them and make them meaningful. Play helps us practice various ways of seeing, feeling, and being, which is a function of stories. I think this. I wonder how, like in theater or writing or film, .</p>

        <p>I befriended a couple professors who communicate in ways that I find compassionate and compatible, which are now my highest priority metrics for my intellectual exchanges. I made an observation to one of my AI lecturers about how fairy tales, which are often authorless yet simultaneously a composition of many minds and tellings, are similar to the stories generated by AI-reliant art, games, and media, which are also authorless in an attributive sense but build upon huge datasets of human creative knowledge. He was not only receptive but really "yes, and"-ed me, and we explored comparisons between GPT and Homer together. It's this kind of encouragement that helps me arrive at new and vital disciplinary connections.</p>

        <p>After my morning strolls, I spend my middays reading and writing and my afternoons designing screens and taking calls. This week I watched a project I designed for last winter publicly launch, as well as some of my midnight product visions get green lights from company leadership. The fruits of my 21st-century labor. After work, I have my daily dancing and cooking break, then after dinner I try to rest. Some nights I just sleep I'm designing my new website, calling my friends, gathering notes for my thesis, and writing about writing a movie one day. On Thursday evenings I walk five minutes down the road to a pilates studio to do mat work. The classes are capped at five people plus the instructor. Somehow this style of pilates makes me feel like the most beautiful thing on the planet. The movements are much less robotic and intimidating than in other classes I've tried, but still invigorating; they remind me of yin yoga stretches mixed with the floor exercises I would do before barre during those ballet lessons last year. Through the slow breaths, I love to feel each muscle folding in my core and releasing in my pelvic cavity. The awareness helps me enjoy my body elsewhere too, whether I'm singing or dancing or noticing how long my hair is getting in the mirror. I got a manicure last week and my nails are already growing out from under the gel. I walked by that same salon in the rain several days ago and thought that the plants potted outside looked greener, too. Somehow this reminded me of all the new ideas I was gathering from classes, and also my better posture after just a couple pilates sessions. I stopped to write in my iPhone notes: a lot of growth can happen in just a few days — life is pretty cool because it changes!</p>

        <p>Other nights I'm out late walking around again. In any case, my evenings are dedicated to creative growth and realizations. My masters is 3 years long. I just divided up my knowledge integration course schedule across the 66 weeks I'll be in school until May 2025. Scary to set plans out so far in the future.</p>

      <p>I had an aspiration for this life years ago, to stay in a walk-up in Europe and drink tea and study and write down my life. I didn't know that I would also love myself this much more, though. It's pretty crazy. I'm able to deeply indulge in the happy scents of the laundromat and the fresh bar of peppermint dark chocolate; I really cherish my yogurt in the morning and spring with excitement when I think to make myself a big bowl of pesto pasta. It's like I know that the world will hurt me again, but that I've got devices now — my hope and my projects, my forgiveness and my sense of play — to metabolize the pain and grow through it. I'm knowing myself as a person. This is a sensation I could never have imagined, and it's very, very recent.</p>

      <p>Getting to know a city is just getting to know how you fit into it. The pace you take, the activities you enjoy most. I realized recently that one of my favorite things in the world is that slow pace people take when they wander around a bookstore. It's a little different from a museum pace because museums are designed with an intended form and order, which can affect the locus of control and incite haste. The bookstore pace I'm talking about, on the other hand, is markedly unhurried, basically aimless. I stopped into a charming local chain one morning called Topping &amp; Company Booksellers. With two floors and many rooms, it was deceivingly big. The children's section had armchairs and a tall bay window, and several of the rooms had round tables where people were stationed, deep in a novel. On my long way out, I walked by a mom and her daughter, one following the other, one languid step at a time. They both silently rotated their gaze around the room, from the tops of the tallest shelves to the bottommost rows of fiction. Curiosity and trepidation make a fun pair in this kind of wandering. I wonder what it would take to make this the world’s usual gait.</p>

      <p>I pick up on the attitudes of some unsatisfied classmates, who think our nascent program is too cursory, uncritical, and unrigorous. Their criticisms are all fair and they remind me of the angry frustrations I had during my interdisciplinary undergraduate program at USC, which was also brand new at the time. But for whatever reason, my attitude is so different this time around, and I can feel a draining cultural chasm between my peers and me. After a bachelor's degree that was even more rocky and disciplinarily divergent than this one, and also three years in the mixer as a freelancing wandering-creative trope, I'm learning to lean fully into activities a younger me would have rolled her eyes at. It feels like I'm rereading an instruction book; I've had a looming sense that I skipped a few chapters of due diligence in creative habit building, so this is an attempt at a redo. I can see how the department is trying to build a shared language; I try my best to take their offerings as exercises for honing my attentiveness and expressiveness.

      Getting to know a person is a lot like getting to know a city: we stitch together sequences of experiences and form our theories, our maps. In getting to know myself, I notice which mental streets I trace most often, and I've concluded that I'm very romantic. And sometimes there is the bad weather, which is unavoidable. At least in Edinburgh, the rain fills alleyways, dark puddles of fears. We see how they handle inclement conditions, then how they dry off after, how their flowers resume their bloom. You’re in the curio shop and the sharon van etten song you know so well comes on. And you’re looking at lothian folk tales Greek pastry shop was so novel at first. In Amsterdam on one of those weekday nights, there was a man in the shared hostel space talking about the metaphysical self. “There is something beyond this," he entreated his bunkmate who was getting ready for bed and only half-listening. "I’m interacting with you and you with me, but it’s not just our bodies. It’s something else.” I’m putting hyaloronic acid on my face without a mirror. The woman next to me pulls out a book with a long Portuguese title. The face is a pretty typeface, I assume it’s a new book. When I'm alone, I go to sleep like I wake up, reciting the line excitedly: "this is my life!"

      Getting to know yourself is a lot like getting to know a city: 

      For example, I've grown inconsistent at maintaining pristine notes and giving myself ample synthesis time, and over the last few years of skirting around, I've become increasingly aware of how urgent it is for me to take my intellectual crystallization seriously. If I can barely conduct the low-hanging ideas into complete works, there's little hope I'll smoothly synthesize the ambitious ones, especially at the foggy intersection I'm in. So I'm quite grateful for the credits dedicated to "knowledge integration" and self-reflection. It also helps that I'm coming in with my own subject matter research and firsthand experiences as a practitioner building a mutual aid community, designing tools, and navigating industry. Compared to undergrad, I find it easier this time to feel love for where I am before coming to judgment; I'm more equipped to stay positive and ask questions when I sense a dialectical dead end. I mark the words of my peers, send lively emails to professors, and try my best to monitor my self-consciousness when I speak. I'm not so interested in finding everything wrong anymore — I just want to take what's useful, respect the rest, and make something new of my own. I'm set on being more understanding. I want to make those around me comfortable.

      The old people in Edinburgh are more tattooed than in any other city I've visited yet. I see blurry roses on their arms when they water plants in their front yards, and splotchy lizards on their legs when they carry groceries across the road. Based on the look of their uneven edges, those tattoos must be 40 to 50 years old, which means they've seen more Earth, sun, and both good and bad days than I have in my whole humble life. Writing this makes me laugh because I'm so obviously in my mid-twenties; the days are both dramatically painful and gainful because I have so few to compare them against! Last night, I scrolled past four different couples my age announcing their engagements on Facebook. Meanwhile, just before seeing those posts, I had used the back of an earring to pop a searing blister on my pinky toe because my belongings were in too much upheaval for me to find my tweezers or sewing kit. I giggled to myself: you might be getting married, but I'm getting resourceful!

      I did, however, do something quite serious recently, on par with marriage: I put a down payment on a condo. It's a three-story loft in a peaceful, walkable part of Ohio. A massive window spans the whole height. There are two bedrooms, two bathrooms, and a gorgeous corner staircase. One of my secret hobbies this past year was looking at homes on Redfin and Zillow; despite my chaotic nomad outlook, I persistently wanted a space to anchor myself. I kept my eyes on mid-sized cities in the US eastern time zone because they're the best for balancing my US-based work and my UK-based studies and are more affordable than the bigger east coast cities. I clicked on this condo the day the listing hit the market — giant windows and exposed brick — and sent it to my parents, who "ooh"-ed as well. I could afford it and it was beautiful, but my mind still rushed through many questions. Am I sure about locking myself into this? They're probably getting so many offers... Maybe I shouldn't because I can't see it in person... Will I even get the loan approved fast enough? While my mind ran, I let my body lead. I made the calls, got a realtor to give me an extensive video tour, filled out the forms, and hired an inspector, and then 72 hours later it was taken off the market, by me. The address has my lucky numbers, and even though I was like the fourth person to make an offer, the sellers miraculously accepted mine. Anyway, I'm still letting my mental reality catch up to this new development. I'll start moving in the last week of December.

      Blended into the old town, the university campus places Renaissance revival architecture right next to blocky post-war buildings. Today I listened to Debussy and walked past cemeteries and cathedrals to the Main Library, a massive brutalist building, to pick up a copy of The Complete Grimm's Fairy Tales. I was specifically seeking Padraic Colum's introduction essay. During our first two-day intensive about the origins and evolution of narrative, the course organizers invited a Scottish storyteller: a spirited older woman with graying cropped hair, very light blue eyes, and a layered bohemian dress. For a strange yet pleasant hour, she performed a tale about selkies, which is Scots for "seal folk" or seals that can turn into humans; a call-and-response folk song; and an unfamiliar and more elaborate rendition of Cinderella. After our applause and wide-eyed questions, she ended with an impromptu soapbox about the lost designation of storytelling in our modern age. Referencing Colum’s essay in which he blames the death of storytelling on the advent of the gas lamp, her passion felt resonant with my own interests in tracing the myth of fire as a metonymy for human invention and play. I got surprisingly emotional during this last message — I felt tears form! — and if I've learned anything at all in my adventures, it's that we should all move closer toward the things that move us on the inside. That's why I dedicated my morning to finding this essay, mulling it over, and meditating on my next expeditions in the worlds of narrative, fairy tale, and modernity.

      It's also noticing just how changing it is Just this summer, through all my travels and even after settling into Edinburgh for a few weeks, I experienced a steady stream of deep-seated doubts. Throughout the period, I often felt like I was retreating or returning to a child version of myself, like anything I encountered in my day-to-day could startle me and make me feel unwelcome. The journey through and out of this state was like dreadful hike, but one I'd known I'd about for a while and did prepare for, however reluctantly. I basically spent a lot of time doing standing meditations and looking at myself in the mirror. I started to see myself how I see my best friends — loving each freckle and wayward tooth and hair — and it became so easy to tell myself to get real! I spent the rest of the season in awe of how my conviction had led me here, walking around Scotland, making money, building cool things, and studying literature. I'm so powerful to be able to reject people's underdeveloped advice without any consequences at all; I'm allowed to control what I take personally, and . Knowing that I have my own place also relieves the accumulating mental claustrophobia, because now my internal world can be more externalized, and this gives me a lot of security. Most of all, I'm lucky to be around tolerant friends. I feel a lot more well.

      On my breaks between calls, I buy groceries or take a walk around the park. I'm seeing familiar faces. I'm starting to recognize the locals in my particular neighborhood:) Oxford loafer shoes, corduroy, canvas boots, overalls. Scruffy terriers, beards and mustaches, dainty tortoiseshell glasses. I got my first facial in a beauty salon on Easter Road. Physical care has climbed my list of love languages recently, so I've decided to integrate more massages and pamperings into my life. The esthetician buttered me up with all kinds of masks and oils, from eucalyptus to neroli, then rubbed hot stones on my face. I imagined each cell in my skin bursting open at the touch of the heat and enveloping in the nutrition of the moisturizers.

      I guess the joke, or the wisdom, is that most cities are actually pretty similar. I like , like most people. Cities, like people, . Even if they seem distinct, they're functionally the same: they are — we are — made to be homes for other people.

      It's jarring how mean I was to myself. Renewed. Like cities, every love is different. When I'm alone, I go to sleep like I wake up, reciting the line excitedly: "this is my life!"

      I can offer this to myself. Cities, like our loved ones, will make space for you if you ask. I loved who i was in that city, even if my effects weren’t absorbed into the rhtym and peace of the people thefe, even though i stood out as cluster of unwelcome anomalies, talked too loud in the grocery store.

      Whether I'm assembling the paragraphs in my journal or attempting to prepare the meal that I crave, I'm practicing how to master the distance between my hands and my volition. Something small within me blossoms with every trial. Sometimes I even forget where I am and who I am to other people. I’m just a momentary conduit of attention, confessing, guessing, assessing, undressing. Creative growth is like making vulnerable little memories with yourself.

      I got a manicure last week and my nails are already growing up from under the gel. I walked by that salon in the rain a few days ago and the plants potted outside look greener, too. A lot of growth in just seven days. Life is pretty cool in that it changes.

      Sometimes people drift and sometimes people stay for a bit longer. Did you know that tattoos don't actually "stain" your skin cells? Tattoo ink is actually trapped by white blood cells called macrophages, and when those cells die, they release the ink for new macrophages to hold onto. Cells pass tattoo ink along the way we pass traditions from generation to generation, like going to the movies for Christmas, or eating meat. The image reminds me of something I read: everything is plurality, that the ways we shift and grow. Each atom rubs itself into the next, encoding between them some special bond unique to their pair.

      This evening, before sitting down to write this, I took myself on a date to the beach. Getting a sense of where my hands meet my volition. Nothing feels better than doing what you intended to do. Life and structures sometimes impede on that agency of will. It’s good to be the master of it.

      I'm having the easiest time I've ever had staying positive and timeblocking. I'm taking responsibility for what I can, and reading about the philosophy of responsibility for instructions on the rest. My mornings are active and joyous. M

      I’ve booked my flights to Amsterdam and London.

      Getting to know someone is a lot like getting to know a city. I guess the joke of it (or the wisdom) is that all cities are actually pretty much the same.

      Getting to know a city is just getting to know how you fit into it. The pace you take, the activities you enjoy most.

      Cutting out photos of my clothes

      I take instructions from Wendy cope

      For months now, been dealing with: “I’d like some time to develop a thoughtful opinion about that”

      I should always expect the best for myself. Moving forward, I promise to believe that I’m very lucky. I need to practice this every day, like exercise. It’s like a mental girder.

      Do calluses stay forever? Can they?

      Being okay with putting in 80%, accepting that the stakes are not that high

      I like when its called a pot instead of bowl

      People playing with fire in the park

      Rosemary oil in my hair for hair growth

      Waking up early

      Life is so weird, we made a lot of stuff and abuses

      experimental in the science world vs in the art world

      Every pizza place was booked or flawed today

      Do i believe in god? I believe in whatever walt whitman said in blades of grass.

      every love is different

      Never get into relationships where youre not appreciated for your full you. Stop researching the people you see as threatening. Love is attention, which can be forcefully directed, but also appreciation, which is a valence, which comes from a sort of inner magic, a sense of belonging to the world.

      Like truly getting to know someone, i will never regret visiting a city. I’ve always learned something about myself, and I will always celebrate the commemorate the time we shared, when we were together. Time space agency

      Tonight, before sitting down to write this, I took myself on a date to the water. Nothing feels better than doing what you intended to do. Life and structures sometimes impede on that agency of will,. It’s good to be the master of it.

      Settling into myself, taking it slow.

      I'm making myself emotionally receptive.

      There is nothing more magical than gratitude. And the way we express gratitude is so unique. We have a lot to be thankful for. This is a . I went to sing to the swans today, and the rain misted my glases and I felt the dampness of the grass seep into the sole of my shoe. And yet I was so happy because it smelled so good outside. When we show people gratitude, their best qualities are blessed with the expectation to grow. People bloom in these conditions. We should all be so lucky. &nbsp;&#x273d;</p>

      </div>      

    </main>
  );
}