import EntryLayout from '../entry-layout';
import Image from 'next/image';
import entryStyles from "../../styles/entry.module.css";

export default function JournalEntryPage() {

  const heroImage = (
      <Image
        className={entryStyles.writingHero}
        src="/journal-graphics/every-love-is-different.jpg"
        alt="Project"
        width={2880}
        height={2025}
        style={{ width: '100%', height: 'auto' }}
        quality={100} 
        priority
      />
  )

    const heroCaption = "Rhys looking out from Calton Hill in Edinburgh, Scotland."

    return (
      <EntryLayout slug="every-love-is-different" heroImage={heroImage} heroCaption={heroCaption}>

        <p><em>While this entry is dear to my heart, it needs some pruning and attention. I know there's an affecting and good piece of writing within this huge piece, and one day I will edit to find it. For now, please accept this work-in-progress in its meadering and mediocrity!</em></p>
        
        <p>I'm currently in a walkable city with a nice income, which means I can end my morning strolls by trying a different local cafe each weekend—and I don't have to be so cheap about it. My routine includes seeing smiling and busy people in the street, or at crosswalks, or in the park with their dogs, then reviewing menus in coffee shop windows to decide whether or not a dirty chai latte is one of the ways I will show myself love today. Where I stay in Abbeyhill is lined with some great Italian delicatessens, plant-based bakeries, and homemade takeaway stops. I begin my days with a cardamom bun when possible, and always stop for matcha if I find it. I get the "daily soups" even when they cost £8. My boots are finally breaking in.</p>

        <p>A year of mottled circumstances has passed since I last told someone I was based out of this time zone. Blackpool, Manchester, Doha, Dubai, Kuala Lumpur, George Town, Renton, Oxford, London, Lisbon, Chicago, St Andrews, Amsterdam, Edinburgh. It doesn't seem to matter whether I spent a few moments in a city or several long months. The temporariness of my stations, which I had to confront every time I thought about which of my present routines were lifelong or conditional, prompted me to treasure where I was and what I was dealing with—no matter how strange or awful—at least once a day. A few standout moments include the hysterical disbelief of finding the bed bugs in Manchester, my mom haggling expertly at the crowded gold souk in Dubai, and the vegetarian feast on Tamil New Year. I appreciate the cities and the people I got to know better in them; I loved laughing with Lumi as she barged into our Oxford Airbnb proudly hoisting a massive watermelon, and dancing on West Sands Beach until the night finally killed the bonfire. I remember my nerves, but also the times I was remarkably cool-headed. I keep the stories and the playlists, the jokes and the gifts, and that mindful saying, "Wherever you go, there you are." These have been pretty meaningful seasons.</p>

        <p>Starting my Masters has been ambitious, but great. I'm still getting used to managing full-time work with the reading and writing deadlines, as well as those burns of momentary embarrassment whenever I say something unduly strained in class because God knows how long it's been since I've been around this many new people. Nonetheless, it's kind of nice to be one of many in a cohort again; the university environment is stimulating and youthful. I feel especially grateful to have faculty stewardship in my interests in narrative theory and the future of technology. I'm coming to my own words for describing narrative: narrative is what is born from the sequence of fragmented experiences, whether presented in words, images, or the passing of life events through time. It's the melding of some given order of information units and the patterns we make between them. It's both the dots and their invisible lines, both the positive and negative space.</p>

        <p>After my morning strolls, I spend my middays reading and writing and my afternoons designing screens and taking calls. This week I watched a project I designed for last winter publicly launch, as well as some of my midnight product visions get green lights from company leadership. After work, I cook dinner, then I enjoy some personal time. I'm designing my new website, calling my friends, gathering notes for my thesis, and writing about writing a movie one day. Other nights I'm out late walking around again. In any case, my evenings are dedicated to creative growth and realizations. My masters is 3 years long. I just divided up my knowledge integration course schedule across the 66 weeks I'll be in school until May 2025. Scary to set plans out so far in the future.</p>
        
        <p>On Thursday evenings I walk five minutes down the road to a pilates studio to do mat work. The classes are capped at five people plus the instructor. Somehow this style of pilates makes me feel like the most beautiful thing on the planet. The movements are much less robotic and intimidating than in other classes I've tried, but still invigorating; they remind me of yin yoga stretches mixed with the floor exercises I would do before barre during those ballet lessons last year. Through the slow breaths, I love to feel each muscle folding in my core and releasing in my pelvic cavity. The awareness helps me enjoy my body elsewhere too, whether I'm singing or dancing or noticing how long my hair is getting in the mirror. I got a manicure last week and my nails are already growing out from under the gel. I walked by that same salon in the rain several days ago and thought that the plants potted outside looked greener, too. Somehow this reminded me of all the new ideas I was gathering from classes, and also my better posture after just a couple pilates sessions. I stopped to write in my iPhone notes: a lot of growth can happen in just a few days—life is pretty cool because it changes!</p>

      <p>I had an aspiration for this life years ago, to stay in a walk-up in Europe and drink tea and study and write down my life. I didn't know that I would also love myself this much more, though. It's pretty crazy. I'm able to deeply indulge in the happy scents of the laundromat and the fresh bar of peppermint dark chocolate; I really cherish my yogurt in the morning and spring with excitement when I think to make myself a big bowl of pesto pasta. It's like I know that I will make mistakes again, but that I've got devices now—my hope and my projects, my forgiveness and my sense of play—to metabolize and grow through them. I'm knowing myself as a person.</p>

      <p>Getting to know a city is just getting to know how you fit into it. The pace you take, the activities you enjoy most. I realized recently that one of my favorite things in the world is that slow pace people take when they wander around a bookstore. It's a little different from a museum pace because museums are designed with an intended form and order, which can affect the locus of control and incite haste. The bookstore pace I'm talking about, on the other hand, is markedly unhurried, basically aimless. I stopped into a charming local chain one morning called Topping &amp; Company Booksellers. With two floors and many rooms, it was deceivingly big. The children's section had armchairs and a tall bay window, and several of the rooms had round tables where people were stationed, deep in a novel. On my long way out, I walked by a mom and her daughter, one following the other, one languid step at a time. They both silently rotated their gaze around the room, from the tops of the tallest shelves to the bottommost rows of fiction. Curiosity and trepidation. I wonder what it would take to make this the world’s usual gait.</p>

      <p>The old people in Edinburgh are more tattooed than in any other city I've visited yet. I see blurry roses on their arms when they water plants in their front yards, and splotchy lizards on their legs when they carry groceries across the road. Based on the look of their uneven edges, those tattoos must be 40 to 50 years old, which means they've seen more Earth, sun, and both good and bad days than I have in my whole humble life. Writing this makes me laugh because I'm so obviously in my mid-twenties; the days are both dramatically painful and gainful because I have so few to compare them against! Last night, I scrolled past four different couples my age announcing their engagements on Facebook. Meanwhile, just before seeing those posts, I had used the back of an earring to pop a searing blister on my pinky toe because my belongings were in too much upheaval for me to find my tweezers or sewing kit. I joked to myself: you might be getting married, but I'm getting resourceful!</p>

      <p>I did, however, do something quite serious recently, on par with marriage: I put a down payment on a condo. It's a three-story loft in a peaceful, walkable part of Ohio. A massive window spans the whole height. There are two bedrooms, two bathrooms, and a gorgeous corner staircase. One of my secret hobbies this past year was looking at homes on Redfin and Zillow; despite my chaotic nomad outlook, I persistently wanted a space to anchor myself. I kept my eyes on mid-sized cities in the US eastern time zone because they're the best for balancing my US-based work and my UK-based studies and are more affordable than the bigger east coast cities. I clicked on this condo the day the listing hit the market—giant windows and exposed brick—and sent it to my parents, who "ooh"-ed as well. I could afford it and it was beautiful, but my mind still rushed through many questions. Am I sure about locking myself into this? They're probably getting so many offers... Maybe I shouldn't because I can't see it in person... Will I even get the loan approved fast enough? While my mind ran, I let my body lead. I made the calls, got a realtor to give me an extensive video tour, filled out the forms, and hired an inspector, and then 72 hours later it was taken off the market, by me. The address has my lucky numbers, and even though I was like the fourth person to make an offer, the sellers miraculously accepted mine. Anyway, I'm still letting my mental reality catch up to this new development. I'll start moving in the last week of December.</p>

      <p>Also, I'm falling in love. Getting to know another person is a lot like getting to know a city: we stitch together sequences of experiences and form our theories, our maps. In getting to know myself, I notice which mental streets I trace most often. I am romantic. I like to appreciate the details in another person. And sometimes there is the bad weather, which is unavoidable. At least in Edinburgh, the rain fills alleyways, dark puddles all day long. We see how they handle inclement conditions, then how they dry off after, how their flowers resume their bloom. You’re in the odd curio shop several neighborhoods away and the Sharon Van Etten song you know so well comes on, and it's familiar but also new. And you’re looking at the book of Lothian folk tales and you'd never thought you'd behold something so unique and intricate before. And you look into the windows of the Greek pastry shop, the one you walk by every day now, and it's like like looking into their eyes, remembering how novel they were to you at first.</p>

      <p>Getting to know yourself is a lot like getting to know a city, too. For example, I've grown inconsistent at maintaining pristine notes and giving myself ample synthesis time, and over the last few years of skirting around, I've become increasingly aware of how urgent it is for me to take my intellectual crystallization seriously. I'm more inclined to appreciate the long walks, the vast, empty parks. If I can barely conduct the low-hanging ideas into complete works, there's little hope I'll smoothly synthesize the ambitious ones, especially at the foggy intersection I'm in. So I'm quite grateful for the credits dedicated to "knowledge integration" and self-reflection, like the benches in odd places that invite me to sit and pause. I have the space to ponder my firsthand experiences as a practitioner building a mutual aid community, designing tools, and navigating industry. Compared to undergrad, I find it easier this time to <em>feel love for where I am before coming to judgment</em>, no longer scrutinizing the traffic or broken sidewalks; I'm more equipped to stay positive and ask questions when I sense a dialectical dead end. I mark the words of my peers, send lively emails to professors, and try my best to monitor my self-consciousness when I speak. I'm not so interested in finding everything wrong anymore—I just want to take what's useful, respect the rest, and make something new of my own. I'm set on being more understanding. I want to make those around me comfortable. I want to find what's hospitable.</p>

      <p>Getting to know yourself is also noticing how resilient you are capable of being. Cities have sewage systems, stormwater management, tree canopies, grass. Just this summer, through all my travels and even after settling into Edinburgh for a few weeks, I experienced a steady stream of deep-seated doubts. Throughout the period, I often felt like I was retreating or returning to a child version of myself, like anything I encountered in my day-to-day could startle me and make me feel unwelcome. The journey through and out of this state was like dreadful hike, but one I'd known about for a while and did prepare for, however reluctantly. I basically spent a lot of time doing standing meditations and looking at myself in the mirror. I started to see myself how I see my best friends—loving each freckle and wayward tooth and hair—and it became so easy to tell myself to get real! I spent the rest of the season in awe of how my conviction had led me here, walking around Scotland, making money, building cool things, and studying literature. I'm so powerful to be able to reject people's underdeveloped advice without any consequences at all; I'm allowed to control what I take personally and not. Knowing that I have my own place also relieves the accumulating mental claustrophobia, because now my internal world can be more externalized, and this gives me a lot of security. Most of all, I'm lucky to be around tolerant friends. I'm not perfect at all of this, but I feel a lot more well.</p>

      <p>On my breaks between calls, I buy groceries or take a walk around the park. I'm seeing familiar faces. I'm starting to recognize the locals in my particular neighborhood. Oxford loafer shoes, corduroy, canvas boots, overalls. Scruffy terriers, beards and mustaches, dainty tortoiseshell glasses. I got my first facial in a beauty salon on Easter Road. Physical care has climbed my list of love languages recently, so I've decided to integrate more massages and pamperings into my life. The esthetician buttered me up with all kinds of masks and oils, from eucalyptus to neroli, then rubbed hot stones on my face. I imagined each cell in my skin bursting open at the touch of the heat and enveloping in the nutrition of the moisturizers.</p>

      <p>I guess the joke, or the wisdom, is that most cities are actually pretty similar. I like promenades and parks and a good view from a bridge and streets that are not too wide nor too thin, like most people. Cities, like people, have beautiful traits that anyone could see as beautiful. And when you get to know someone like that, they inspire you to be more of those things too. Better, kinder, wiser. Less reactive, more patient. Even if they seem different, cities and people are similar: they are—we are—made to be homes for other people. They're meant to spot and house kindred beings. They will make space for you if you ask.</p>

      <p>But cities, like people, are all different. I'm flashing between Doha, Amsterdam, London, and Edinburgh now. Yes, they looked different. Every love is different. But what I remember most is how I shifted between each home, what has been pushed to evolve, what has stayed the same against all odds. In some ways, I feel like I'm tall enough to see from a certain vantage point now, or have the courage now finally to go to the beach alone early in the morning for the first time. In other ways, I see that I seek out the best noodle soup spot wherever I go, and I'm always looking for a comfortable place to sit and read. Whether I'm articulating the difficult idea to a friend or attempting to share enough but not too much at the dinner party, I'm always practicing how to master the distance between my presence and my volition. Something small within me blossoms with every trial. Sometimes I even forget where I am and who I am to other people. I’m just a momentary conduit of attention, confessing, guessing, assessing, undressing. And I can claim the right to self-love even if I wasn't absorbed in the rhythm and peace of the place perfectly, even if I stood out as a cluster of anomalies, talked too loud in the grocery store. Growth is like making vulnerable little memories with yourself and the place you're in, the company you're with. And like truly getting to know someone, I will never regret visiting a city. I’ve always gained something of myself and I will always celebrate that, and respect my agency and that of others to continue their journeys. Settings and people can decide to stay or leave from memory to memory, and that is lovely and okay.</p>
      
      <p>Did you know that tattoos don't actually "stain" your skin cells? Tattoo ink is actually trapped by white blood cells called macrophages, and when those cells die, they release the ink for new macrophages to hold onto. Cells pass tattoo ink along the way we pass traditions from generation to generation, like going to the movies for Christmas, or eating meat. The image reminds me of something I read somewhere I don't remember: the ways we shift and grow come from being changed by our relationships. Each atom rubs itself into the next, encoding between them some special bond unique to their pair.</p>

      <p>Lastly, as this has gotten too long, there is also always more to explore in both cities and people. You can keep coming back to a place and it will be different every time. New things appear and old things become slightly seasoned with time or change. I'm reckoning with the bits of me that are on the move, including my relationship with God, perfectionism, sleep, my appearance, and how experimental and fringe I want my career to be. Currently, I believe in whatever Walt Whitman talks about in <em>Leaves of Grass</em>, I'm growing okay with putting in 80% and acknowledging when the stakes are not that high, I wear a sleep mask and put rosemary oil in my hair and try to wake up early, and I'm just trying to settle into myself and take it slow.</p>
      
     <p>Mostly, I notice that I now how I exclaim to myself excitedly "this is my life!" throughout the day and feel grace and humor and like I want to click my heels with joy. It's silly, but I hope this new habit isn't an impermanent one, because there is nothing more magical than love and gratitude. I went to sing to the swans today, and the rain misted my glasses and I felt the dampness of the grass seep into the sole of my shoe. And yet I was so happy because it smelled so good outside. And I thought about how when we show love and gratitude to people and places and anything really, their best qualities are blessed with the expectation to stay, bloom, and grow. &nbsp;&#x273d;</p>

      </EntryLayout>
  );
}